# Generated by Django 4.1.7 on 2023-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Name')),
                ('body', models.CharField(db_index=True, max_length=100, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
